[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.typescript"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = [
  "npm install --omit=dev",
  "cd client && npm install --omit=dev && npm run build",
  "cd .. && npx tsc"
]

[start]
cmd = "node dist/server/index.js"
